export default {
  fontFamily: "'Source Sans Pro', Helvetica, Arial, sans-serif",
  white: '#fff',
  primaryColor: '#32d36b',
  secondaryColor: '#f4f4f4',
  thirdColor: '#808080',
  inputTextColor: '#181825',
  titleColor: '#4c4c4c',
  smoothDangerColor: 'rgba(255,0,0,.05)',
  dangerColor: 'red',
  inputBorder: '#ccc',
  tabBorder: '#555',
  backgroundColor: '#eee',
  cardBackground: '#333',
  cardColor: '#ccc',
};
